from serial import Serial
from time import sleep
serial = Serial("/dev/ttyUSB0", baudrate=115200)

serial.write(b'\n0 encoder\n')
sleep(0.001)
response = serial.read_until(expected=b'\n')
print(response)
serial.write(b'\n1 encoder\n')
sleep(0.001)
response = serial.read_until(expected=b'\n')
print(response)

serial.write(b'\n0 r\n')
sleep(0.001)
response = serial.read_until(expected=b'\n')
print(response)
serial.write(b'\n1 r\n')
sleep(0.001)
response = serial.read_until(expected=b'\n')
print(response)


serial.write(b'\n0 t\n')
sleep(0.001)
response = serial.read_until(expected=b'\n')
print(response)

serial.write(b'\n1 t\n')
sleep(0.001)
response = serial.read_until(expected=b'\n')
print(response)


serial.write(b'\n0 d 0.0 0.3\n')
sleep(0.001)
response = serial.read_until(expected=b'\n')
print(response)
sleep(1)
serial.write(b'\n1 d 0.0 0.3\n')
sleep(0.001)
response = serial.read_until(expected=b'\n')
print(response)
sleep(5)
serial.write(b'\n0 d 0.3 0.3\n')
sleep(0.001)
response = serial.read_until(expected=b'\n')
print(response)
sleep(1)
serial.write(b'\n1 d 0.3 0.3\n')
sleep(0.001)
response = serial.read_until(expected=b'\n')
print(response)
serial.close()