all:
	pandoc interface.md --pdf-engine=xelatex --listings --toc --standalone -V geometry:a4paper -V geometry:margin=2cm -V mainfont="DejaVu Serif" -V monofont="DejaVu Sans Mono"  -f gfm -o interface.pdf
